# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5LhgljOcDDUMqOVbFOdUYxwHvr_Thxy
"""

for i in range(65,70):
  for j in range(65,i+1):
    print(chr(i),end=" ")
  print("")

for i in range(65,70):
  for j in range(65,i+1):
    print(chr(j),end=" ")
  print("")

for i in range(1,6):
  for j in range(i,6):
    print(" ",end=" ")
  for k in range(1,i+1):
    print(k,end=" ")
  print("")

for i in range(1,6):
  for j in range(i,6):
    print(" ",end=" ")
  for k in range(1,i+1):
    print("*",end=" ")
  print("")

for i in range(1,6):
  for j in range(1,i+1):
    print(" ",end=" ")
  for k in range(1,6):
    print("*",end=" ")
  print("")

for i in range(1,6):
  for j in range(i,6):
    print(" ",end=" ")
  for k in range(1,6):
    print("*",end=" ")
  print("")

for i in range(1,6):
  for j in range(i,6):
    print(" ",end=" ")
  for k in range(1,6):
    print(k,end=" ")
  print("")

for i in range(1,6):
  for j in range(i,6):
    print(" ",end=" ")
  for k in range(65,70):
    print(chr(k),end=" ")
  print("")

for i in range(1,6):
  for j in range(1,i+1):
    print(" ",end=" ")
  for k in range(i,6):
    print(k,end=" ")
  print("")

for i in range(65,70):
  for j in range(65,i+1):
    print(" ",end=" ")
  for k in range(i,70):
    print(chr(k),end=" ")
  print("")

for i in range(65,70):
  for j in range(65,i+1):
    print(" ",end=" ")
  for k in range(65,70-(i-65)):
    print(chr(k),end=" ")
  print("")

for i in range(1,6):
  for j in range(1,i+1):
    print(" ",end=" ")
  for k in range(1,6-(i-1)):
    print(k,end=" ")
  print("")

for i in range(69,64,-1):
  for j in range(i,70):
    print(chr(j),end=" ")
  print("")

for i in range(5):
  for j in range(6):
    if i==0 or i==5-1 or j==0 or j==6-1:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print("")